Address Sanitizer
ROCmSoftwarePlatform/rocRAND pull request #161
Opened 2021-01-12 09:28 UTC by eidenyoshida

2021-01-12 17:30 UTC, saadrahim reviewed
Looks good, need to see results on CI

2021-01-12 18:02 UTC, eidenyoshida commented
Debug build is supposed to run with address sanitizer enabled. Do we expect to see extra verbose output from our tests when this is enabled?

2021-01-12 18:43 UTC, saadrahim commented
Only if it detects something. Not sure if there is a default output.

2021-01-13 22:50 UTC, saadrahim requested changes

2021-01-13 22:50 UTC, saadrahim commented on CMakeLists.txt
> +        set ( HSAKMT_LINK_FLAGS "${HSAKMT_LINK_FLAGS}" -shared-libasan )
we should change the variable name. HSAKMT is a rocm project. Let's call it rocRAND or something generic.

2021-01-13 22:55 UTC, saadrahim commented on CMakeLists.txt
> +        set ( HSAKMT_LINK_FLAGS "${HSAKMT_LINK_FLAGS}" -shared-libasan )
Code needs to move down. we need to customize for us.

2021-01-14 22:37 UTC, b-sumner commented
I think this looks fine (but agree that HSAKMT can be changed).  I am wondering though about a debug build without the sanitizer.  The sanitizer runtime can add a fair amount of memory overhead (in addition to the other runtime overhead)  which could be problematic in some cases.

2021-02-04 16:59 UTC, saadrahim commented
@eidenyoshida you may want to finish this off.

2021-02-17 23:04 UTC, eidenyoshida commented
Opened a separate PR to add sanitizer flags to install script

2021-02-17 23:04 UTC, closed without merging